/**
 * Maps common nationality strings to flag emoji.
 * Falls back to 🏳️ if no match is found.
 */
const NATIONALITY_FLAGS: Record<string, string> = {
  american: "🇺🇸",
  usa: "🇺🇸",
  "united states": "🇺🇸",
  australian: "🇦🇺",
  australia: "🇦🇺",
  british: "🇬🇧",
  english: "🇬🇧",
  uk: "🇬🇧",
  "united kingdom": "🇬🇧",
  canadian: "🇨🇦",
  canada: "🇨🇦",
  french: "🇫🇷",
  france: "🇫🇷",
  german: "🇩🇪",
  germany: "🇩🇪",
  italian: "🇮🇹",
  italy: "🇮🇹",
  spanish: "🇪🇸",
  spain: "🇪🇸",
  brazilian: "🇧🇷",
  brazil: "🇧🇷",
  colombian: "🇨🇴",
  colombia: "🇨🇴",
  mexican: "🇲🇽",
  mexico: "🇲🇽",
  argentinian: "🇦🇷",
  argentina: "🇦🇷",
  russian: "🇷🇺",
  russia: "🇷🇺",
  ukrainian: "🇺🇦",
  ukraine: "🇺🇦",
  czech: "🇨🇿",
  "czech republic": "🇨🇿",
  polish: "🇵🇱",
  poland: "🇵🇱",
  hungarian: "🇭🇺",
  hungary: "🇭🇺",
  romanian: "🇷🇴",
  romania: "🇷🇴",
  serbian: "🇷🇸",
  serbia: "🇷🇸",
  croatian: "🇭🇷",
  croatia: "🇭🇷",
  dutch: "🇳🇱",
  netherlands: "🇳🇱",
  swedish: "🇸🇪",
  sweden: "🇸🇪",
  norwegian: "🇳🇴",
  norway: "🇳🇴",
  danish: "🇩🇰",
  denmark: "🇩🇰",
  japanese: "🇯🇵",
  japan: "🇯🇵",
  korean: "🇰🇷",
  korea: "🇰🇷",
  "south korean": "🇰🇷",
  chinese: "🇨🇳",
  china: "🇨🇳",
  thai: "🇹🇭",
  thailand: "🇹🇭",
  filipina: "🇵🇭",
  filipino: "🇵🇭",
  philippines: "🇵🇭",
  vietnamese: "🇻🇳",
  vietnam: "🇻🇳",
  indian: "🇮🇳",
  india: "🇮🇳",
  latina: "🌎",
  "puerto rican": "🇵🇷",
  "puerto rico": "🇵🇷",
  cuban: "🇨🇺",
  cuba: "🇨🇺",
  dominican: "🇩🇴",
  "dominican republic": "🇩🇴",
  venezuelan: "🇻🇪",
  venezuela: "🇻🇪",
  portuguese: "🇵🇹",
  portugal: "🇵🇹",
  greek: "🇬🇷",
  greece: "🇬🇷",
  turkish: "🇹🇷",
  turkey: "🇹🇷",
  israeli: "🇮🇱",
  israel: "🇮🇱",
  lebanese: "🇱🇧",
  lebanon: "🇱🇧",
  irish: "🇮🇪",
  ireland: "🇮🇪",
  scottish: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  welsh: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  belgian: "🇧🇪",
  belgium: "🇧🇪",
  austrian: "🇦🇹",
  austria: "🇦🇹",
  swiss: "🇨🇭",
  switzerland: "🇨🇭",
  finnish: "🇫🇮",
  finland: "🇫🇮",
  estonian: "🇪🇪",
  estonia: "🇪🇪",
  latvian: "🇱🇻",
  latvia: "🇱🇻",
  lithuanian: "🇱🇹",
  lithuania: "🇱🇹",
  slovak: "🇸🇰",
  slovakia: "🇸🇰",
  slovenian: "🇸🇮",
  slovenia: "🇸🇮",
  bulgarian: "🇧🇬",
  bulgaria: "🇧🇬",
  albanian: "🇦🇱",
  albania: "🇦🇱",
  montenegrin: "🇲🇪",
  montenegro: "🇲🇪",
  "bosnian": "🇧🇦",
  bosnia: "🇧🇦",
  "north macedonian": "🇲🇰",
  macedonia: "🇲🇰",
  icelandic: "🇮🇸",
  iceland: "🇮🇸",
  "new zealander": "🇳🇿",
  "new zealand": "🇳🇿",
  "south african": "🇿🇦",
  "south africa": "🇿🇦",
  egyptian: "🇪🇬",
  egypt: "🇪🇬",
  moroccan: "🇲🇦",
  morocco: "🇲🇦",
  nigerian: "🇳🇬",
  nigeria: "🇳🇬",
  kenyan: "🇰🇪",
  kenya: "🇰🇪",
  ethiopian: "🇪🇹",
  ethiopia: "🇪🇹",
  ghanaian: "🇬🇭",
  ghana: "🇬🇭",
  jamaican: "🇯🇲",
  jamaica: "🇯🇲",
  bahamian: "🇧🇸",
  bahamas: "🇧🇸",
  barbadian: "🇧🇧",
  barbados: "🇧🇧",
  trinidadian: "🇹🇹",
  "trinidad and tobago": "🇹🇹",
  haitian: "🇭🇹",
  haiti: "🇭🇹",
  panamanian: "🇵🇦",
  panama: "🇵🇦",
  "costa rican": "🇨🇷",
  "costa rica": "🇨🇷",
  ecuadorian: "🇪🇨",
  ecuador: "🇪🇨",
  peruvian: "🇵🇪",
  peru: "🇵🇪",
  chilean: "🇨🇱",
  chile: "🇨🇱",
  uruguayan: "🇺🇾",
  uruguay: "🇺🇾",
  paraguayan: "🇵🇾",
  paraguay: "🇵🇾",
  bolivian: "🇧🇴",
  bolivia: "🇧🇴",
  salvadoran: "🇸🇻",
  "el salvador": "🇸🇻",
  guatemalan: "🇬🇹",
  guatemala: "🇬🇹",
  honduran: "🇭🇳",
  honduras: "🇭🇳",
  nicaraguan: "🇳🇮",
  nicaragua: "🇳🇮",
  taiwanese: "🇹🇼",
  taiwan: "🇹🇼",
  indonesian: "🇮🇩",
  indonesia: "🇮🇩",
  malaysian: "🇲🇾",
  malaysia: "🇲🇾",
  singaporean: "🇸🇬",
  singapore: "🇸🇬",
  cambodian: "🇰🇭",
  cambodia: "🇰🇭",
  laotian: "🇱🇦",
  laos: "🇱🇦",
  burmese: "🇲🇲",
  myanmar: "🇲🇲",
  nepalese: "🇳🇵",
  nepal: "🇳🇵",
  "sri lankan": "🇱🇰",
  "sri lanka": "🇱🇰",
  bangladeshi: "🇧🇩",
  bangladesh: "🇧🇩",
  pakistani: "🇵🇰",
  pakistan: "🇵🇰",
  afghan: "🇦🇫",
  afghanistan: "🇦🇫",
  iranian: "🇮🇷",
  iran: "🇮🇷",
  iraqi: "🇮🇶",
  iraq: "🇮🇶",
  "saudi arabian": "🇸🇦",
  "saudi arabia": "🇸🇦",
  emirati: "🇦🇪",
  uae: "🇦🇪",
  "united arab emirates": "🇦🇪",
  qatari: "🇶🇦",
  qatar: "🇶🇦",
  kuwaiti: "🇰🇼",
  kuwait: "🇰🇼",
  omani: "🇴🇲",
  oman: "🇴🇲",
  bahraini: "🇧🇭",
  bahrain: "🇧🇭",
  jordanian: "🇯🇴",
  jordan: "🇯🇴",
  palestinian: "🇵🇸",
  palestine: "🇵🇸",
  syrian: "🇸🇾",
  syria: "🇸🇾",
  yemeni: "🇾🇪",
  yemen: "🇾🇪",
  georgian: "🇬🇪",
  georgia: "🇬🇪",
  armenian: "🇦🇲",
  armenia: "🇦🇲",
  azerbaijani: "🇦🇿",
  azerbaijan: "🇦🇿",
  kazakh: "🇰🇿",
  kazakhstan: "🇰🇿",
  uzbek: "🇺🇿",
  uzbekistan: "🇺🇿",
  turkmen: "🇹🇲",
  turkmenistan: "🇹🇲",
  kyrgyz: "🇰🇬",
  kyrgyzstan: "🇰🇬",
  tajik: "🇹🇯",
  tajikistan: "🇹🇯",
  mongolian: "🇲🇳",
  mongolia: "🇲🇳",
};

export function getFlagEmoji(nationality: string | null | undefined): string {
  if (!nationality) return "🏳️";
  const lower = nationality.toLowerCase().trim();
  return NATIONALITY_FLAGS[lower] ?? "🏳️";
}
