import React from "react";
import "@testing-library/jest-dom";

// Mock lucide-react icons — add any icon used in components here
vi.mock("lucide-react", () => {
  const icon = (testId: string) => () => <span data-testid={testId} />;
  return {
    Film: icon("icon-film"),
    Users: icon("icon-users"),
    Zap: icon("icon-zap"),
    Trophy: icon("icon-trophy"),
    Sparkles: icon("icon-sparkles"),
    Shield: icon("icon-shield"),
    ArrowRight: icon("icon-arrow-right"),
    ArrowLeft: icon("icon-arrow-left"),
    Settings: icon("icon-settings"),
    History: icon("icon-history"),
    Plus: icon("icon-plus"),
    BarChart2: icon("icon-bar-chart"),
    LogOut: icon("icon-log-out"),
    Star: icon("icon-star"),
    Package: icon("icon-package"),
    Home: icon("icon-home"),
    User: icon("icon-user"),
    Lock: icon("icon-lock"),
    Eye: icon("icon-eye"),
    EyeOff: icon("icon-eye-off"),
    AlertCircle: icon("icon-alert-circle"),
    CheckCircle: icon("icon-check-circle"),
    X: icon("icon-x"),
    Calendar: icon("icon-calendar"),
    Clock: icon("icon-clock"),
    TrendingUp: icon("icon-trending-up"),
    Wallet: icon("icon-wallet"),
    ChevronDown: icon("icon-chevron-down"),
    Menu: icon("icon-menu"),
    Bell: icon("icon-bell"),
    Search: icon("icon-search"),
    Edit: icon("icon-edit"),
    Trash: icon("icon-trash"),
    Check: icon("icon-check"),
    Info: icon("icon-info"),
    Download: icon("icon-download"),
    Upload: icon("icon-upload"),
    ExternalLink: icon("icon-external-link"),
    ChevronRight: icon("icon-chevron-right"),
    ChevronLeft: icon("icon-chevron-left"),
    Loader2: icon("icon-loader"),
    RefreshCw: icon("icon-refresh"),
    Copy: icon("icon-copy"),
    Share: icon("icon-share"),
    Heart: icon("icon-heart"),
    Bookmark: icon("icon-bookmark"),
    Tag: icon("icon-tag"),
    Filter: icon("icon-filter"),
    SortAsc: icon("icon-sort-asc"),
    SortDesc: icon("icon-sort-desc"),
    Grid: icon("icon-grid"),
    List: icon("icon-list"),
    Map: icon("icon-map"),
    Globe: icon("icon-globe"),
    Link: icon("icon-link"),
    Image: icon("icon-image"),
    Video: icon("icon-video"),
    Music: icon("icon-music"),
    Mic: icon("icon-mic"),
    Camera: icon("icon-camera"),
    Maximize: icon("icon-maximize"),
    Minimize: icon("icon-minimize"),
    Play: icon("icon-play"),
    Pause: icon("icon-pause"),
    Square: icon("icon-square"),
    Circle: icon("icon-circle"),
    Triangle: icon("icon-triangle"),
    Hexagon: icon("icon-hexagon"),
    Diamond: icon("icon-diamond"),
    Award: icon("icon-award"),
    Medal: icon("icon-medal"),
    Crown: icon("icon-crown"),
    Flame: icon("icon-flame"),
    Bolt: icon("icon-bolt"),
    Lightning: icon("icon-lightning"),
  };
});

// Make React available globally for JSX transform
global.React = React;
